// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:445e9cca-d77f-4105-b906-8b3e39c6bfe8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hOzE7BiQj",
    "aws_user_pools_web_client_id": "47096om2rs19hq7dhfe0tpo705",
    "aws_content_delivery_bucket": "website-20181121155214--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d371kiirq5a7hl.cloudfront.net"
};


export default awsmobile;
